### PR TITLE
Port to Forge 1.18.2

### PR DESCRIPTION
**Pull request by CanadianBaconBoi**
Ported this to forge 1.18.2 using Architectury loom.

Main change is not bundling cloth config as it is seen as better practice to keep them separated in Forge.

I would recommend creating a branch on the base repo called 'forge', I will change the PR branch when it is made.

Note. I had to remove the developer nametag easter egg as it caused issues with Applied Energistics

### CODE REVIEW

**Comment by maximumpower55** [comment]
Thing to note is that there are major changes to the whole mod in dev right now

**Comment by CanadianBaconBoi** [comment]
If you'd like I could port that branch, or I could wait for it to become stable to port it.

**Comment by maximumpower55** [comment]
> If you'd like I could port that branch, or I could wait for it to become stable to port it.

You should wait for it to be in a stable state / release

**Comment by Traben-0** [comment]
for now it might be easiest to just port from main yeah, i've made a forge branch for you

**Comment by CanadianBaconBoi** [comment]
Thank you, I've changed the base branch.

**Comment by Traben-0** [comment]
the next release will have quite heavy reworks

**Comment by maximumpower55** [comment]
> for now it might be easiest to just port from main yeah, i've made a forge branch for you

The branch should be named architectury imo

**Comment by CanadianBaconBoi** [comment]
I think that an architectury branch would be better suited for a mod with a common codebase that can compile to forge, fabric, and quilt.

**Comment by Traben-0** [comment]
jsut made an Architectury one

**Comment by maximumpower55** [comment]
> I think that an architectury branch would be better suited for a mod with a common codebase that can compile to forge, fabric, and quilt.

Oh you didn't port it to a common codebase? That would be make more sense imo

**Comment by CanadianBaconBoi** [comment]
@Traben-0 I could setup the Architectury branch for common builds

**Comment by maximumpower55** [comment]
> @Traben-0 I could setup the Architectury branch for common builds

I can help with porting it to a common codebase now that you have ported it to forge

**Comment by CanadianBaconBoi** [comment]
This was more of a quick port to forge from the existing codebase, it would make more sense for the dev branch to be developed for a common codebase as a design idea rather an afterthought though.

**Comment by Traben-0** [comment]
it's going to be ideal for the future to ahve the common codebase

**Comment by maximumpower55** [comment]
I would rather wait for anything more major to happen with this pr after the heavy reworks are in a stable state

**Comment by CanadianBaconBoi** [comment]
I would then refactor the dev branch with that design philosophy so there wouldn't have to be a seperate branch for a common codebase.

**Comment by Traben-0** [comment]
we can just have the seperate forge version for now then

**Comment by maximumpower55** [comment]
> the next release will have quite heavy reworks

Aka #48

**Pull request merged**
