### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by GodGun968**

### CODE REVIEW

**Review by SungHerobrine97 — COMMENTED** [review]
little fix

**Comment by GodGun968** [comment]
What? What should I need to do

**Comment by SungHerobrine97** [comment]
just look.not for anything

**Comment by GodGun968** [comment]
Do I need to do something? or just wait

**Comment by SungHerobrine97** [comment]
Contact these developer for review, I'm not a devloper for this repo.

**Comment by GodGun968** [comment]
Well, I thought you were one of the developers.

**Pull request merged**
