### PR TITLE
Update ru_ru.json

### PR DESCRIPTION
**Pull request by Felix14-v2**
New translations, updated old ones

### CODE REVIEW

**Review by Traben-0 — APPROVED** [review]

**Comment by Traben-0** [comment]
Will merge for 4.3.1

**Comment by Felix14-v2** [comment]
By the way, it seems that the "Off" state for the "Allow broken paths" setting is untranslatable. If you could add a string for it, I would expand this PR with a new translation

**Comment by Traben-0** [comment]
It uses the vanilla gui object for "off", it should automatically swap to using the official Russian when you change languages  does it not?

**Comment by Felix14-v2** [comment]
> it should automatically swap to using the official Russian when you change languages does it not?

Strange, for some reason this doesn't happen for me. Perhaps this is an incompatibility with the Language Reload mod, i'll check it.

**Comment by Traben-0** [comment]
i found teh cause something dumb on my end, didn't notice ofcourse cause i'm using english

**Pull request merged**
